
name: Build C++ Program

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Compile C++ Program
        shell: msys2 {0}
        run: |
          g++ main.cpp -o program.exe -static -static-libgcc -static-libstdc++

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program-windows
          path: program.exe
